dist: focal
language: java
before_install:
  - sudo apt -qq update
  - sudo apt install -y libblkid-dev liblz4-tool device-tree-compiler
script:
  - ./gradlew check
  - ./gradlew clean
  - ./integrationTest.py
